//image_speed=0;
//image_index=0;
counter=0;
hp=300;
hp_bar=instance_create_depth(x,y-20,-1,obj_hp);
obj_hp.image_xscale=hp;
obj_hp.image_yscale=2;
hit_done=0;
image_xscale=12;
image_yscale=12;
global.enemy++